apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      containers:
        - name: api
          image: api:v1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
name: api               # можно использовать как host
spec:
  selector:
    app: api-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080        # service port
      targetPort: 8080  # container port
      nodePort: 30001
