version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - m2:/root/.m2
    networks:
      - micro-api
  internal:
    build: ./internal
    environment:
      PG_USERNAME: postgres
      PG_PASSWORD: 123
    volumes:
      - m2:/root/.m2
    networks:
      - micro-api
      - micro-db
  docker-pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - micro-db

volumes:
  m2:
  pg:

networks:
  micro-db: {}
  micro-api: {}