apiVersion: apps/v1
kind: Deployment
metadata:
  name: greedy-deployment
  labels:
    app: greedy-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greedy-pod
  template:
    metadata:
      labels:
        app: greedy-pod
    spec:
      containers:
        - name: greedy
          image: greedy:v1.1
          resources:
            requests:
              memory: "400Mi"
              cpu: 100m
            limits:
              memory: "400Mi"
              cpu: 100m
          env:
            - name: GREEDY_MODE
              value: CPU
              #value: MEM
