apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-config
data:
  # file-like keys
  application-props: |
    micronaut.application.name=internal
    micronaut.server.port=8080
    
    datasources.pg.url=jdbc:postgresql://docker-pg.db-namespace:5432/postgres
    datasources.pg.driver-class-name=org.postgresql.Driver
    datasources.pg.db-type=postgres
    datasources.pg.dialect=POSTGRES
    datasources.pg.username=${PG_USERNAME}
    datasources.pg.password=${PG_PASSWORD}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-deployment
  labels:
    app: internal-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-pod
  template:
    metadata:
      labels:
        app: internal-pod
    spec:
      containers:
        - name: internal
          image: internal:v1.1
          ports:
            - containerPort: 8080
          env:
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: pg-username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: pg-password
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: internal-config
            items:
              - key: "application-props"
                path: "application.properties"
---
apiVersion: v1
kind: Service
metadata:
  name: internal        # можно использовать как host
spec:
  selector:
    app: internal-pod
  ports:
    - protocol: TCP
      port: 8080        # service port
      targetPort: 8080  # container port
