apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-claim
spec:
  storageClassName: ""
  volumeName: pg-persistent-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
